{% set name = "cargo-make" %}
{% set version = "0.37.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sagiegurari/cargo-make/archive/refs/tags/{{ version }}.tar.gz
  sha256: a7f6f7332862442e6020e8d8b2568a6fa8eed28156be0dddd61982e1e644cf02

build:
  binary_relocation: false
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
  run:

test:
  commands:
    - test -f $PREFIX/bin/cargo-make  # [unix]
    - test -f $PREFIX/bin/makers  # [unix]
    - if not exist %PREFIX%\bin\cargo-make.exe exit 1  # [win]
    - if not exist %PREFIX%\bin\makers.exe exit 1  # [win]
    - cargo-make make --help
    - makers -h

about:
  home: https://github.com/sagiegurari/cargo-make
  summary: 'Rust task runner and build tool.'
  description: |
    The cargo-make task runner enables to define and configure sets of tasks and run them as a flow.
    A task is a command, script, rust code, or other sub tasks to execute.
    Tasks can have dependencies which are also tasks that will be executed before the task itself.
    With a simple toml based configuration file, you can define a multi platform build script that
    can run build, test, generate documentation, run bench tests, run security validations and more,
    executed by running a single command.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://sagiegurari.github.io/cargo-make/

extra:
  recipe-maintainers:
    - sagiegurari
    - MementoRC
